name: 0trrmar
base: core22
version: '0'
summary: Single-line elevator pitch
description: |
  This is my-snap's description.

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  hello:
    command: bin/0trrmar

package-repositories:
  - formats: [deb]
    key-id: 8B5E181F3D689E73E16C3014EAAFEE64EF92AAA0
    type: apt
    url: https://archive.swiftlang.xyz/ubuntu/
    suites: [jammy]
    components: [main]

parts:
  0trrmar:
    plugin: nil
    build-packages: [swiftlang]
    source: .
    override-build: |
      set -euo pipefail; IFS=$'\n\t' 
      swift build --configuration=release --static-swift-stdlib
      mkdir -p $CRAFT_PART_INSTALL/bin/
      bin_path=`swift build --configuration=release --show-bin-path`
      cp $bin_path/$CRAFT_PART_NAME $CRAFT_PART_INSTALL/bin/
