name: 0trrmar
base: core20
version: '0'
summary: Single-line elevator pitch
description: |
  This is my-snap's description.

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  0trrmar:
    command: bin/0trrmar
  1cep9ug:
    command: bin/1cep9ug

package-repositories:
  - type: apt
    formats: [deb]
    url: https://archive.swiftlang.xyz/ubuntu/
    key-id: 8B5E181F3D689E73E16C3014EAAFEE64EF92AAA0
    suites: [focal]
    components: [main]

parts:
  swift-package:
    plugin: nil
    build-packages: [swiftlang]
    source: .
    override-build: |
      set -euo pipefail; IFS=$'\n\t' 
      swift build --configuration=release --static-swift-stdlib
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      bin_path=`swift build --configuration=release --show-bin-path`
      cp `find $bin_path -maxdepth 1 -type f -executable` $SNAPCRAFT_PART_INSTALL/bin/
